server:
  port: 7001
eureka:
  instance:
    hostname: eureka-server1
  client:
    #fasle 表示不向注册中心注册自己
    register-with-eureka: false
    #false 表示自己就是注册中心，职责是维护服务，而不是检索服务
    fetch-registry: false
    service-url:
      #设置与eureka交互的地址，查询服务和服务注册的地址
      defaultZone: http://eureka-server1:7001/eureka/
  server:
    #关闭自我保护机制，保证不可用服务及时剔除
    enable-self-preservation: false
    #设置时间内无心跳立即剔除
    eviction-interval-timer-in-ms: 2000