server:
  port: 8081
spring:
  application:
    name: pay-mode
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.144.235.110:3306/zxc?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Yiqinuli2019!
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      #采样率值 介于0到1之间，1表示全部采集
      probability: 1
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zxc.sgg.entity

eureka:
  client:
    #表示是否将自己注册进eureka
    register-with-eureka: true
    #是否从注册中心获取已有的服务注册信息
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/ #,http://localhost:7002/eureka/
  instance:
    instance-id: pay-mode8081
    prefer-ip-address: true
    #Eureka 服务端在收到最后一次心跳后等待时间上限（单位是秒，默认90s），超时将剔除
    lease-expiration-duration-in-seconds: 2
    #Eureka 客户端向服务端发送心跳的时间间隔，单位是秒（默认30s）
    lease-renewal-interval-in-seconds: 1