server:
  port: 9004
spring:
  application:
    name: payment
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        #server-addr: 192.168.88.128:1111
management:
  endpoints:
    web:
      exposure:
        include: '*'