server:
  port: 3344
spring:
  application:
    name: spring-cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/yang_bike/eureka-config.git
          #search-paths:
            #- configclient
      label: master
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'