server:
  port: 8803
spring:
  application:
    name: stream-consumer
  cloud:
    stream:
      binders:
        defaultRabbit: #表示定义的名称，用于与binding整合
          type: rabbit #消息组件类型
          environment: #设置rabbitmq的相关环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: #服务的整合处理
        input: #通道名称
          destination: studyExchange  #表示要使用的交换机名称
          content-type: application/json #设置消息类型，本次为json
          binder: defaultRabbit #设置要绑定的消息服务的具体设置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5
    instance-id: receive-8803.com
    prefer-ip-address: true