server:
  port: 8401
spring:
  application:
    name: sentilnel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
        datasource:
          # 名字随意
          ds:
            nacos:
              # nacos的访问地址，，根据上面准备工作中启动的实例配置
              server-add: localhost:8848
              # nacos中存储规则的groupId

management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true