server:
  port: 8082
spring:
  application:
    name: pay-mode

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.144.235.110:3306/zxc?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Yiqinuli2019!
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zxc.sgg.entity

eureka:
  client:
    #表示是否将自己注册进eureka
    register-with-eureka: true
    #是否从注册中心获取已有的服务注册信息
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/ #,http://localhost:7002/eureka/
  instance:
    instance-id: pay-mode8082
    prefer-ip-address: true