server:
  port: 80
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
logging:
  level:
    com.zxc.sgg.service.UserModeService: debug
